services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./.env
    ports:
      - 5533:1433
    volumes:
      - test-vol:/var/opt/mssql
volumes:
  test-vol:
    external: true